const TOKENS = [
  { name: "USDC", symbol: "USDC", address: "0xA0b8...eB48" },
  { name: "Ethereum", symbol: "ETH" },
  { name: "Tether", symbol: "USDT", address: "0xdAC1...1ec7" },
  { name: "Base ETH", symbol: "ETH" },
  { name: "Wrapped Bitcoin", symbol: "WBTC", address: "0x2260...C599" },
  { name: "USD Coin", symbol: "USDC", address: "0xaf88...5831" },
  { name: "USDC", symbol: "USDC", address: "0x8335...2913" },
  { name: "USDT0", symbol: "USDT", address: "0xFd08...Cbb9" },
];

const RepaymentData = [
  {
    id: 16,
    name: "Wrapped ETH WETH",
    price: "$1,501.63",
    hour: "▲ 0.96%",
    day: "▼ 15.79%",
    fdv: "$3.4B",
    volume: "$28.6M",
    chart: "📉",
  },
  {
    id: 17,
    name: "BNB BNB",
    price: "$545.20",
    hour: "▲ 0.85%",
    day: "▼ 7.36%",
    fdv: "$669.8M",
    volume: "$28.6M",
    chart: "📉",
  },
  {
    id: 18,
    name: "Cardano ADA",
    price: "$0.48",
    hour: "▲ 1.25%",
    day: "▼ 5.12%",
    fdv: "$16.8B",
    volume: "$12.4M",
    chart: "📈",
  },
  {
    id: 19,
    name: "Solana SOL",
    price: "$95.32",
    hour: "▲ 2.15%",
    day: "▲ 8.45%",
    fdv: "$41.2B",
    volume: "$89.7M",
    chart: "📈",
  },
  {
    id: 20,
    name: "Polkadot DOT",
    price: "$7.84",
    hour: "▼ 0.32%",
    day: "▼ 3.21%",
    fdv: "$9.8B",
    volume: "$15.3M",
    chart: "📉",
  },
  {
    id: 21,
    name: "Avalanche AVAX",
    price: "$35.67",
    hour: "▲ 1.85%",
    day: "▲ 12.45%",
    fdv: "$12.4B",
    volume: "$45.2M",
    chart: "📈",
  },
  {
    id: 22,
    name: "Chainlink LINK",
    price: "$14.23",
    hour: "▲ 0.95%",
    day: "▼ 2.34%",
    fdv: "$7.4B",
    volume: "$18.9M",
    chart: "📉",
  },
  {
    id: 23,
    name: "Polygon MATIC",
    price: "$0.89",
    hour: "▲ 1.45%",
    day: "▼ 4.56%",
    fdv: "$8.2B",
    volume: "$25.6M",
    chart: "📉",
  },
  {
    id: 24,
    name: "Uniswap UNI",
    price: "$5.67",
    hour: "▼ 0.75%",
    day: "▼ 6.78%",
    fdv: "$4.2B",
    volume: "$15.8M",
    chart: "📉",
  },
  {
    id: 25,
    name: "Cosmos ATOM",
    price: "$9.45",
    hour: "▲ 2.34%",
    day: "▲ 5.67%",
    fdv: "$3.5B",
    volume: "$12.4M",
    chart: "📈",
  },
  // Continuing with similar pattern for remaining entries...
  {
    id: 115,
    name: "Algorand ALGO",
    price: "$0.34",
    hour: "▲ 1.23%",
    day: "▼ 3.45%",
    fdv: "$2.5B",
    volume: "$8.9M",
    chart: "📉",
  },
  {
    id: 116,
    name: "VeChain VET",
    price: "$0.025",
    hour: "▲ 0.98%",
    day: "▼ 2.34%",
    fdv: "$1.8B",
    volume: "$5.6M",
    chart: "📉",
  },
  {
    id: 24,
    name: "Uniswap UNI",
    price: "$5.67",
    hour: "▼ 0.75%",
    day: "▼ 6.78%",
    fdv: "$4.2B",
    volume: "$15.8M",
    chart: "📉",
  },
  {
    id: 25,
    name: "Cosmos ATOM",
    price: "$9.45",
    hour: "▲ 2.34%",
    day: "▲ 5.67%",
    fdv: "$3.5B",
    volume: "$12.4M",
    chart: "📈",
  },
  // Continuing with similar pattern for remaining entries...
  {
    id: 115,
    name: "Algorand ALGO",
    price: "$0.34",
    hour: "▲ 1.23%",
    day: "▼ 3.45%",
    fdv: "$2.5B",
    volume: "$8.9M",
    chart: "📉",
  },
  {
    id: 116,
    name: "VeChain VET",
    price: "$0.025",
    hour: "▲ 0.98%",
    day: "▼ 2.34%",
    fdv: "$1.8B",
    volume: "$5.6M",
    chart: "📉",
  },  {
    id: 24,
    name: "Uniswap UNI",
    price: "$5.67",
    hour: "▼ 0.75%",
    day: "▼ 6.78%",
    fdv: "$4.2B",
    volume: "$15.8M",
    chart: "📉",
  },
  {
    id: 25,
    name: "Cosmos ATOM",
    price: "$9.45",
    hour: "▲ 2.34%",
    day: "▲ 5.67%",
    fdv: "$3.5B",
    volume: "$12.4M",
    chart: "📈",
  },
  // Continuing with similar pattern for remaining entries...
  {
    id: 115,
    name: "Algorand ALGO",
    price: "$0.34",
    hour: "▲ 1.23%",
    day: "▼ 3.45%",
    fdv: "$2.5B",
    volume: "$8.9M",
    chart: "📉",
  },
  {
    id: 116,
    name: "VeChain VET",
    price: "$0.025",
    hour: "▲ 0.98%",
    day: "▼ 2.34%",
    fdv: "$1.8B",
    volume: "$5.6M",
    chart: "📉",
  },  {
    id: 24,
    name: "Uniswap UNI",
    price: "$5.67",
    hour: "▼ 0.75%",
    day: "▼ 6.78%",
    fdv: "$4.2B",
    volume: "$15.8M",
    chart: "📉",
  },
  {
    id: 25,
    name: "Cosmos ATOM",
    price: "$9.45",
    hour: "▲ 2.34%",
    day: "▲ 5.67%",
    fdv: "$3.5B",
    volume: "$12.4M",
    chart: "📈",
  },
  // Continuing with similar pattern for remaining entries...
  {
    id: 115,
    name: "Algorand ALGO",
    price: "$0.34",
    hour: "▲ 1.23%",
    day: "▼ 3.45%",
    fdv: "$2.5B",
    volume: "$8.9M",
    chart: "📉",
  },
  {
    id: 116,
    name: "VeChain VET",
    price: "$0.025",
    hour: "▲ 0.98%",
    day: "▼ 2.34%",
    fdv: "$1.8B",
    volume: "$5.6M",
    chart: "📉",
  },  {
    id: 24,
    name: "Uniswap UNI",
    price: "$5.67",
    hour: "▼ 0.75%",
    day: "▼ 6.78%",
    fdv: "$4.2B",
    volume: "$15.8M",
    chart: "📉",
  },
  {
    id: 25,
    name: "Cosmos ATOM",
    price: "$9.45",
    hour: "▲ 2.34%",
    day: "▲ 5.67%",
    fdv: "$3.5B",
    volume: "$12.4M",
    chart: "📈",
  },
  // Continuing with similar pattern for remaining entries...
  {
    id: 115,
    name: "Algorand ALGO",
    price: "$0.34",
    hour: "▲ 1.23%",
    day: "▼ 3.45%",
    fdv: "$2.5B",
    volume: "$8.9M",
    chart: "📉",
  },
  {
    id: 116,
    name: "VeChain VET",
    price: "$0.025",
    hour: "▲ 0.98%",
    day: "▼ 2.34%",
    fdv: "$1.8B",
    volume: "$5.6M",
    chart: "📉",
  },  {
    id: 24,
    name: "Uniswap UNI",
    price: "$5.67",
    hour: "▼ 0.75%",
    day: "▼ 6.78%",
    fdv: "$4.2B",
    volume: "$15.8M",
    chart: "📉",
  },
  {
    id: 25,
    name: "Cosmos ATOM",
    price: "$9.45",
    hour: "▲ 2.34%",
    day: "▲ 5.67%",
    fdv: "$3.5B",
    volume: "$12.4M",
    chart: "📈",
  },
  // Continuing with similar pattern for remaining entries...
  {
    id: 115,
    name: "Algorand ALGO",
    price: "$0.34",
    hour: "▲ 1.23%",
    day: "▼ 3.45%",
    fdv: "$2.5B",
    volume: "$8.9M",
    chart: "📉",
  },
  {
    id: 116,
    name: "VeChain VET",
    price: "$0.025",
    hour: "▲ 0.98%",
    day: "▼ 2.34%",
    fdv: "$1.8B",
    volume: "$5.6M",
    chart: "📉",
  },  {
    id: 24,
    name: "Uniswap UNI",
    price: "$5.67",
    hour: "▼ 0.75%",
    day: "▼ 6.78%",
    fdv: "$4.2B",
    volume: "$15.8M",
    chart: "📉",
  },
  {
    id: 25,
    name: "Cosmos ATOM",
    price: "$9.45",
    hour: "▲ 2.34%",
    day: "▲ 5.67%",
    fdv: "$3.5B",
    volume: "$12.4M",
    chart: "📈",
  },
  // Continuing with similar pattern for remaining entries...
  {
    id: 115,
    name: "Algorand ALGO",
    price: "$0.34",
    hour: "▲ 1.23%",
    day: "▼ 3.45%",
    fdv: "$2.5B",
    volume: "$8.9M",
    chart: "📉",
  },
  {
    id: 116,
    name: "VeChain VET",
    price: "$0.025",
    hour: "▲ 0.98%",
    day: "▼ 2.34%",
    fdv: "$1.8B",
    volume: "$5.6M",
    chart: "📉",
  },  {
    id: 24,
    name: "Uniswap UNI",
    price: "$5.67",
    hour: "▼ 0.75%",
    day: "▼ 6.78%",
    fdv: "$4.2B",
    volume: "$15.8M",
    chart: "📉",
  },
  {
    id: 25,
    name: "Cosmos ATOM",
    price: "$9.45",
    hour: "▲ 2.34%",
    day: "▲ 5.67%",
    fdv: "$3.5B",
    volume: "$12.4M",
    chart: "📈",
  },
  // Continuing with similar pattern for remaining entries...
  {
    id: 115,
    name: "Algorand ALGO",
    price: "$0.34",
    hour: "▲ 1.23%",
    day: "▼ 3.45%",
    fdv: "$2.5B",
    volume: "$8.9M",
    chart: "📉",
  },
  {
    id: 116,
    name: "VeChain VET",
    price: "$0.025",
    hour: "▲ 0.98%",
    day: "▼ 2.34%",
    fdv: "$1.8B",
    volume: "$5.6M",
    chart: "📉",
  },  {
    id: 24,
    name: "Uniswap UNI",
    price: "$5.67",
    hour: "▼ 0.75%",
    day: "▼ 6.78%",
    fdv: "$4.2B",
    volume: "$15.8M",
    chart: "📉",
  },
  {
    id: 25,
    name: "Cosmos ATOM",
    price: "$9.45",
    hour: "▲ 2.34%",
    day: "▲ 5.67%",
    fdv: "$3.5B",
    volume: "$12.4M",
    chart: "📈",
  },
  // Continuing with similar pattern for remaining entries...
  {
    id: 115,
    name: "Algorand ALGO",
    price: "$0.34",
    hour: "▲ 1.23%",
    day: "▼ 3.45%",
    fdv: "$2.5B",
    volume: "$8.9M",
    chart: "📉",
  },
  {
    id: 116,
    name: "VeChain VET",
    price: "$0.025",
    hour: "▲ 0.98%",
    day: "▼ 2.34%",
    fdv: "$1.8B",
    volume: "$5.6M",
    chart: "📉",
  },  {
    id: 24,
    name: "Uniswap UNI",
    price: "$5.67",
    hour: "▼ 0.75%",
    day: "▼ 6.78%",
    fdv: "$4.2B",
    volume: "$15.8M",
    chart: "📉",
  },
  {
    id: 25,
    name: "Cosmos ATOM",
    price: "$9.45",
    hour: "▲ 2.34%",
    day: "▲ 5.67%",
    fdv: "$3.5B",
    volume: "$12.4M",
    chart: "📈",
  },
  // Continuing with similar pattern for remaining entries...
  {
    id: 115,
    name: "Algorand ALGO",
    price: "$0.34",
    hour: "▲ 1.23%",
    day: "▼ 3.45%",
    fdv: "$2.5B",
    volume: "$8.9M",
    chart: "📉",
  },
  {
    id: 116,
    name: "VeChain VET",
    price: "$0.025",
    hour: "▲ 0.98%",
    day: "▼ 2.34%",
    fdv: "$1.8B",
    volume: "$5.6M",
    chart: "📉",
  },  {
    id: 24,
    name: "Uniswap UNI",
    price: "$5.67",
    hour: "▼ 0.75%",
    day: "▼ 6.78%",
    fdv: "$4.2B",
    volume: "$15.8M",
    chart: "📉",
  },
  {
    id: 25,
    name: "Cosmos ATOM",
    price: "$9.45",
    hour: "▲ 2.34%",
    day: "▲ 5.67%",
    fdv: "$3.5B",
    volume: "$12.4M",
    chart: "📈",
  },
  // Continuing with similar pattern for remaining entries...
  {
    id: 115,
    name: "Algorand ALGO",
    price: "$0.34",
    hour: "▲ 1.23%",
    day: "▼ 3.45%",
    fdv: "$2.5B",
    volume: "$8.9M",
    chart: "📉",
  },
  {
    id: 116,
    name: "VeChain VET",
    price: "$0.025",
    hour: "▲ 0.98%",
    day: "▼ 2.34%",
    fdv: "$1.8B",
    volume: "$5.6M",
    chart: "📉",
  },  {
    id: 24,
    name: "Uniswap UNI",
    price: "$5.67",
    hour: "▼ 0.75%",
    day: "▼ 6.78%",
    fdv: "$4.2B",
    volume: "$15.8M",
    chart: "📉",
  },
  {
    id: 25,
    name: "Cosmos ATOM",
    price: "$9.45",
    hour: "▲ 2.34%",
    day: "▲ 5.67%",
    fdv: "$3.5B",
    volume: "$12.4M",
    chart: "📈",
  },
  // Continuing with similar pattern for remaining entries...
  {
    id: 115,
    name: "Algorand ALGO",
    price: "$0.34",
    hour: "▲ 1.23%",
    day: "▼ 3.45%",
    fdv: "$2.5B",
    volume: "$8.9M",
    chart: "📉",
  },
  {
    id: 116,
    name: "VeChain VET",
    price: "$0.025",
    hour: "▲ 0.98%",
    day: "▼ 2.34%",
    fdv: "$1.8B",
    volume: "$5.6M",
    chart: "📉",
  },  {
    id: 24,
    name: "Uniswap UNI",
    price: "$5.67",
    hour: "▼ 0.75%",
    day: "▼ 6.78%",
    fdv: "$4.2B",
    volume: "$15.8M",
    chart: "📉",
  },
  {
    id: 25,
    name: "Cosmos ATOM",
    price: "$9.45",
    hour: "▲ 2.34%",
    day: "▲ 5.67%",
    fdv: "$3.5B",
    volume: "$12.4M",
    chart: "📈",
  },
  // Continuing with similar pattern for remaining entries...
  {
    id: 115,
    name: "Algorand ALGO",
    price: "$0.34",
    hour: "▲ 1.23%",
    day: "▼ 3.45%",
    fdv: "$2.5B",
    volume: "$8.9M",
    chart: "📉",
  },
  {
    id: 116,
    name: "VeChain VET",
    price: "$0.025",
    hour: "▲ 0.98%",
    day: "▼ 2.34%",
    fdv: "$1.8B",
    volume: "$5.6M",
    chart: "📉",
  },  {
    id: 24,
    name: "Uniswap UNI",
    price: "$5.67",
    hour: "▼ 0.75%",
    day: "▼ 6.78%",
    fdv: "$4.2B",
    volume: "$15.8M",
    chart: "📉",
  },
  {
    id: 25,
    name: "Cosmos ATOM",
    price: "$9.45",
    hour: "▲ 2.34%",
    day: "▲ 5.67%",
    fdv: "$3.5B",
    volume: "$12.4M",
    chart: "📈",
  },
  // Continuing with similar pattern for remaining entries...
  {
    id: 115,
    name: "Algorand ALGO",
    price: "$0.34",
    hour: "▲ 1.23%",
    day: "▼ 3.45%",
    fdv: "$2.5B",
    volume: "$8.9M",
    chart: "📉",
  },
  {
    id: 116,
    name: "VeChain VET",
    price: "$0.025",
    hour: "▲ 0.98%",
    day: "▼ 2.34%",
    fdv: "$1.8B",
    volume: "$5.6M",
    chart: "📉",
  },
  {
    id: 117,
    name: "Stellar XLM",
    price: "$0.12",
    hour: "▲ 1.45%",
    day: "▲ 4.56%",
    fdv: "$3.2B",
    volume: "$9.8M",
    chart: "📈",
  }];

export { TOKENS, RepaymentData };
